<div>
    {{--
    @livewire(\Modules\Geo\Filament\Widgets\LocationMapWidget::class)
    --}}
    @livewire(\Modules\Geo\Filament\Widgets\LocationMapTableWidget::class)
    {{--
    @livewire(\Modules\Blog\Filament\Widgets\SampleChartWidget::class)
    --}}
</div>
