<?php

return [
    1 => [
        'label' => 'iiiiii',
        'link' => '444.0',
        'menu' => '2.0',
        'sort' => '4',
        'id' => 1,
        'parent' => null,
        'class' => null,
        'depth' => null,
        'role_id' => null,
    ],
    2 => [
        'label' => '1',
        'link' => '444.0',
        'menu' => '2.0',
        'sort' => '4.0',
        'id' => 2,
        'parent' => null,
        'class' => null,
        'depth' => null,
        'role_id' => null,
    ],
    3 => [
        'label' => '77',
        'link' => '444.0',
        'menu' => '2.0',
        'sort' => '4.0',
        'id' => 3,
        'parent' => null,
        'class' => null,
        'depth' => null,
        'role_id' => null,
    ],
    4 => [
        'label' => '444',
        'link' => '444',
        'menu' => '2',
        'sort' => 4,
        'id' => 4,
        'parent' => null,
        'class' => null,
        'depth' => null,
        'role_id' => null,
    ],
    5 => [
        'label' => '555',
        'link' => '555',
        'menu' => '2',
        'sort' => 5,
        'id' => 5,
        'parent' => null,
        'class' => null,
        'depth' => null,
        'role_id' => null,
    ],
    6 => [
        'label' => '999',
        'link' => 'uuu',
        'menu' => '2',
        'sort' => 6,
        'id' => 6,
        'parent' => null,
        'class' => null,
        'depth' => null,
        'role_id' => null,
    ],
    7 => [
        'label' => 'uuu',
        'link' => 'iii',
        'menu' => '2',
        'sort' => 7,
        'id' => 7,
        'parent' => null,
        'class' => null,
        'depth' => null,
        'role_id' => null,
    ],
    8 => [
        'label' => 'oo',
        'link' => 'uuu',
        'menu' => '2.0',
        'sort' => 7,
        'id' => 8,
        'parent' => 0,
        'class' => null,
        'depth' => 0,
        'role_id' => null,
    ],
];
